[tool.coverage.run]
source_pkgs = ["app", "ota_proxy"]
branch = true

[tool.coverage.report]
omit = ["app/*pb2*"]
show_missing = true

[tool.black]
exclude = '''(
  app/otaclient_v2_pb2.py |
  app/otaclient_v2_pb2_grpc.py
)'''

[tool.pytest.ini_options]
log_auto_indent = true
log_format = "%(asctime)s %(levelname)s %(filename)s %(funcName)s,%(lineno)d %(message)s"
log_cli = true
log_cli_level = "INFO"
testpaths = ["/ota-client/tests"]