[tool.black]
line-length = 88
target-version = ['py38']
include = '''(
  otaclient.*\.pyi?$
)'''
extend-exclude = '''(
  .*_v2_pb2.*
)'''

[tool.coverage.run]
source_pkgs = ["otaclient.app"]
branch = false

[tool.coverage.report]
omit = [".*_v2_pb2.*"]
show_missing = true

[tool.pyright]
exclude = ["**/__pycache__"]
ignore = [".*_v2_pb2.*"]
pythonVersion = "3.8"

[tool.pytest.ini_options]
asyncio_mode = "auto"
log_auto_indent = true
log_format = "%(asctime)s %(levelname)s %(filename)s %(funcName)s,%(lineno)d %(message)s"
log_cli = true
log_cli_level = "INFO"
testpaths = ["/ota-client/tests"]