[tool.black]
line-length = 90
target-version = ['py38']
exclude = '''(
  app/proto/otaclient_v2_pb2.py |
  app/proto/otaclient_v2_pb2_grpc.py
)'''

[tool.coverage.run]
source_pkgs = ["app"]
branch = true

[tool.coverage.report]
omit = ["app/proto/*pb2*"]
show_missing = true

[tool.pytest.ini_options]
log_auto_indent = true
log_format = "%(asctime)s %(levelname)s %(filename)s %(funcName)s,%(lineno)d %(message)s"
log_cli = true
log_cli_level = "INFO"
addopts = "--cov=app"
testpaths = ["/ota-client/tests"]