version: "3"
services:
  tester:
    build:
      context: ../
      dockerfile: ./docker/test_base/Dockerfile
    image: ota-test_base
    network_mode: bridge
    command: "python3 -m pytest"
    container_name: ota-test
    volumes:
      - ../pyproject.toml:/ota-client/pyproject.toml:ro
      - ../.flake8:/ota-client/.flake8:ro
      - ../otaclient:/ota-client/otaclient:ro
      - ../tests:/ota-client/tests:ro
