name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install build
        run: >-
          python -m pip install build

      - name: build a binary
        run: >-
          python -m
          build
          --wheel
          --outdir dist/
          .

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            proto/pb2/dist/*.whl

      - name: bumpup otaclient_pb2 version
        run: |
          echo $(($(cat .version)+1)) > proto/.version

      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: update otaclient_pb2 version
