name: test CI

on: [pull_request]

jobs:
  pytest_with_coverage:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml requests
          for pathfile in $(find ./ -name "requirements*.txt" -type f); do
             pip install -r $pathfile
          done
      # pytest
      - name: Install test dependencies
        run: |
          python -m pip install pytest pytest-mock pytest-custom_exit_code pytest-cov
      - name: Execute pytest with coverage
        run: |
          set -o pipefail
          sudo $pythonLocation/bin/python -m pytest --cov-report term-missing --cov=app ./tests | tee pytest-coverage.txt
      # export the coverage report to the comment!
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
  python_lint_check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: | 
          python -m pip install black
      - name: Lint codes without modification
        run: | 
          black . --check